name: PRCOP WORKFLOW
on:
  pull_request:
    types: [opened]
jobs:
  prcop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prcop
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
